version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: iherb_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - app_net

  api:
    build: ./backend
    container_name: iherb_api
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app_net
    ports:
      - "8081:8080"
    volumes:
      - uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: iherb_frontend
    restart: always
    depends_on:
      - api
    ports:
      - "8080:3000"
    networks:
      - app_net
    volumes:
      - uploads:/app/uploads

volumes:
  postgres_data:
  uploads:                        

networks:
  app_net:
    driver: bridge
